import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Serif } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import {CartDrawer } from "./componets/CartDrawer";
import { LanguageProvider } from "./i18n/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoSerif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SHBCDC",
  description: "Generated by create next app",
};

const phone = "+919990867867";
const displayPhone = "+91 99908 67867";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoSerif.variable} antialiased`}
      >
        <LanguageProvider>
          <CartProvider>
            <CartDrawer phone={phone} displayPhone={displayPhone} />
            {children}
          </CartProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
